### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by mbuttin** [alexander-pick/MKMTool#13]
Hi, sorry for the newb question...

I've download the compiled app, edit the config.xml file, addind the data of my token from mkm.
But when I launch the soft, I got "(404) Introuvable" error. So the soft didn't download anything and I still got only my 2 basic files in the folder. So when clicking on anything, it tells me some csv files are missing.

So, what's wrong with me ? :)

**Comment by tomasjanak** [comment]
Hello, try pressing the "Update local product list" button, that downloads the CSV files, but my guess is something else is wrong if you're getting 404. When you click the "Account Info" (bottom right), does it show anything? 404 generally means it can't find the server at all, which would be strange (I mean...you were connected to the internet when you tried it, right?). Maybe your firewall is blocking the connection?

**Comment by mbuttin** [comment]
Hi, thanks for the answer.
Of course, I'm connected to the internet :)
I just try with my avast shutted down and it's still the same, 404 error.
Both buttons give me a "can't find mkminventory.csv" error.

Just in case it's something stupid like that : I'm on windows 7 32bits...

**Comment by alexander-pick** [comment]
The URL of the API backend changed and needs a fix. The new URL is now:

https://api.cardmarket.com

I am currently very busy, but can try to push a source change and new binaries this weekend.

**Comment by tomasjanak** [comment]
This has already been changed in the February patch, so only the binaries would need to be updated.

**Comment by alexander-pick** [comment]
Ah I forgot ;) Ok So I will just update the bins at saturday, that should fix the issue for most. It was my MKMeye project which needs the URL update than.

**Comment by ChrisW1980** [comment]
Hi, I did a few changes and fixes to both MKMTool and Eye but they need more testing. I can send you the code / compiled tool if you are willing to help testing.

**Comment by mbuttin** [comment]
Ho yes, please. Will be able to test only next week, but will do :)

**Comment by ChrisW1980** [comment]
Hi,
I have uploaded a compiled version to my OneDrive account. You still need to enter your security details in the config_template.xml and rename it to config.xml. Feel free to contact me if you have any questions. I know that "Check for cheap deals" is not working. I need to look into the problem there. I have also added a box to the right of the price log where you can easily ship multiple orders. However, it gives an error if empty. Will fix it this weekend.

[https://1drv.ms/u/s!Ap_TxsubHNZng4RH2BIOFw27YzVsOg](MKMTool)

**Comment by tomasjanak** [comment]
> 
> 
> Hi,
> I have uploaded a compiled version to my OneDrive account. You still need to enter your security details in the config_template.xml and rename it to config.xml. Feel free to contact me if you have any questions. I know that "Check for cheap deals" is not working. I need to look into the problem there. I have also added a box to the right of the price log where you can easily ship multiple orders. However, it gives an error if empty. Will fix it this weekend.
> 
> [https://1drv.ms/u/s!Ap_TxsubHNZng4RH2BIOFw27YzVsOg](MKMTool)

Hi,
I have been working on a couple updates for the past three weeks, fixing check for cheap deals being one of them, there was a couple of issues. I am now working on one last new feature (pricing cards from an external list loaded from CSV), I'll probably finish it the during the upcoming week and then ask Alexander to merge it here. For now I have at least put it on my github so you can take a look at what is coming not to do the same thing twice: https://github.com/tomasjanak/MKMTool/tree/prescribedPrices (change log has all the major points, you can also go through the individual commits if you want to).

**Comment by mbuttin** [comment]
@ChrisW1980 
Works like a charm, thanks so much.
@tomasjanak 
Can't wait to use this "check for cheap deal" feature and also pricing an external list (using grading, right ?). Thanks :)

**Comment by tomasjanak** [comment]
> 
> 
> @tomasjanak
> Can't wait to use this "check for cheap deal" feature and also pricing an external list (using grading, right ?). Thanks :)

Indeed, my main motivation was to make it as robust as possible - there are a couple tools online you can use but they usually require some specific detail or not take some into account (like condition, language, foil etc.) and just give you lowest price or something easy. With the module I am working on (actually just finished, now onto testing and debugging) you can have as many or as few details about each card in the list and MKMTool will still correctly process it and set a realistic price for it using the same mechanism we use for the price update and/or fetching the "price guide" prices from MKM (trend, lowest price, average sell price etc.).

**Comment by tomasjanak** [comment]
Since this is resolved and links to the old version with wrong addresses has been taken down, I will close this issue.
