### ISSUE TITLE
Updating Prices doesn't work

### ISSUE THREAD

**Issue by gammelhust** [alexander-pick/MKMTool#2]
Hey, 
I just tried your program, but somehow the program just crashes without any errors. (My OS is Windows 10, but also tried it on Win 7).

Hope I can help to improve this program.
(If you need more info please ask)

**Comment by alexander-pick** [comment]
Was the token etc. inserted correctly in the xml config file?

**Comment by ptacki** [comment]
I cannot see any solution for this here, and I have the same problem. It just crushes as in 'application has start working and will now close'. The token should be correct as it downloaded the inventory, also the other buttons work, it crushes only on Updating Prices, as soon as I click it.

**Comment by alexander-pick** [comment]
Can you try to run it with fiddler or some other reverse proxy and check for an error?

**Comment by ptacki** [comment]
Sorry man, I'm a real noob in those things. I never heard about fiddler. I downloaded it but have no idea how to 'run the tool' with it.
