### ISSUE TITLE
Built version

### ISSUE THREAD

**Issue by mbuttin** [alexander-pick/MKMTool#20]
Hi all,

I'm quite an experienced Magic Player but I'm really a poor computer skilled guy...
So, I don't know how to build a github project. Embarrassing, right ?
Readme file tell me I should find a built version here : https://tomasjanak.github.io/MKMTool0.7.0.zip

But it looks to deadly-404 me...

So, could I find it anywhere ? Or could I get some help ?

Thanks folks, and sorry to disturb you from the great job you're doing on this soft :)

**Comment by tomasjanak** [comment]
Hi,

you must be somehow looking at an old version of the readme, the new link is https://tomasjanak.github.io/MKMTool0.7.0.2.zip

**Comment by mbuttin** [comment]
Work like a charm, thanks !
Quick question regarding pricing a csv file : is ther an example of this kind of CSV, regarding differents fields ?
Thx :)

**Comment by tomasjanak** [comment]
Well, not really, but all the possible fields and all the details about the format are described here: https://github.com/alexander-pick/MKMTool#csv-card-lists-in-mkmtool
For the pricing, the only really important fields are Name and Expansion, although even the expansion can be evaluated automatically (oldest, newest etc.), so if you want to you, can get away with a really simple file that has just one column with the Name.
