### ISSUE TITLE
logfile contains only the text "System.Xml.XmlDocument"

### ISSUE THREAD

**Issue by yorii** [alexander-pick/MKMTool#24]
input file:
[mkmmr.csv.txt](https://github.com/alexander-pick/MKMTool/files/3744451/mkmmr.csv.txt)
output log:
https://pastebin.com/dPMcHi6t
settings:
![image](https://user-images.githubusercontent.com/7960287/67104249-e50a8000-f1c6-11e9-939c-3093d9a837f9.png)

The file generated, log18102019-1641.log, contains only the word "System.Xml.XmlDocument".

**Comment by yorii** [comment]
PS: I'm sorry, I just noticed the two failed cards were Negates, which could relate to the issue #23

**Comment by tomasjanak** [comment]
Fixed in 02cd9499240ae4789d3970cc0344e68fc8641d54 and c659d5a8acc1ab7b61c32002fe80325dcee53e3e
Although the error messages are in german and after the first failed article, all subsequent fail as well, but not much we can do about that on our side.
