### ISSUE TITLE
"100 articles updated successfully, 1 failed" every time, and logfile is empty file.

### ISSUE THREAD

**Issue by yorii** [alexander-pick/MKMTool#26]
Hello and thank you for all the great fixes in the latest version!

But in this 0.7.0.4 version I for some reason get a failure of some kind with every price update, although 100 updates also succeed so there doesn't seem to be any real issue:
![image](https://user-images.githubusercontent.com/7960287/67880338-bed9ce00-fb3e-11e9-869c-139c0610456e.png)

The logfile it creates comes out as 0 bytes:
![image](https://user-images.githubusercontent.com/7960287/67880495-fe081f00-fb3e-11e9-825f-4fbdbe0e4418.png)

**Comment by tomasjanak** [comment]
Hi, I fixed that already two days after the initial fixes (https://github.com/alexander-pick/MKMTool/commit/33208fb68b814bc25548ba122d943862897dfe30) and also re-uploaded the .zip file if that's what you are using (the name and path is the same, but it should be corrected), are you using that version?
