### ISSUE TITLE
Tag transformation in MkmTool import

### ISSUE THREAD

**Issue by s-hadz** [alexander-pick/MKMTool#28]
Hello Alx,

Do you know if there's is a way to convert the column "Tag" from Delver's Lens export (.csv) to Mkmtool's integration as column "Comment" to export to Mkm(notTools)?

I would like to  transform the "tag" option from Delvers Lens to be the "comment" option section in Mkm(notTools)

Thanks for your hard work !

**Comment by tomasjanak** [comment]
A bit late to comment, but if I understand correctly all you just need is to rename the column "Tag" in your exported csv to "Comments" and upload it using the Price External List module to export the cards (despite the name, it does not actually have to do any appraisal, it can directly upload to MKM, see documentation for details).
