### ISSUE TITLE
Price update has some flaws

### ISSUE THREAD

**Issue by friscoMad** [alexander-pick/MKMTool#3]
I have been modifying the code to check for underpriced cards in my stock and found some flaws:

- If there are less than 4 offers exactly the same as yours it does not do anything, for old cards or promo it is not that strange for that to happen.
- It takes into account your own offers if they are inside the bottom 4 (and will be if you run it more than once).
- Even if you ask for at least the same quality it is checking later to be the exact same quality, so if a NM is cheaper than EX then it is not taken into consideration.

**Comment by alexander-pick** [comment]
thanks for the heads up, I will look into this.

**Comment by tomasjanak** [comment]
Hi frisco,

I have made some modifications to MKMTool which Alexander merged today to his repository, adding some new parameters to the algorithm for updating prices and making all of them customizable from the GUI. All the points you raised have been addressed:

- You can now change the minimum number of items required for the price to be computed and updated
- Your own offers are no longer taken into account no matter their price
- You can now set whether you want to take into account either 1) only matching condition, 2) any matching or better condition, or 3) matching or better, but better only if there is at least one more expensive card in matching condition (this is intended to handle the most common situation, that is EXC and NM cards having similar prices - now they can also be treated similarly) 

TJ
