### ISSUE TITLE
cant get import in price external to work

### ISSUE THREAD

**Issue by roxart** [alexander-pick/MKMTool#30]
cant get it to work tried to do csv manually to test always doesnt find anything:
Error with importing line #2, article will be ignored: Neither product ID, English name, or localized name + language was found, cannot identify the card.
Error with importing line #3, article will be ignored: Neither product ID, English name, or localized name + language was found, cannot identify the card.

can you guys give me a sample csv that works so i can see what i might do wrong?
thanks

(i tried this:
Quantity;Name;Expansion;Foil
3;Force of Virtue;Modern Horizons; 
1;Fae of Wishes; Throne of Eldraine;foil
)

**Comment by tomasjanak** [comment]
The documentation for the file format is here: https://github.com/alexander-pick/MKMTool#CSV-Card-Lists-in-MKMTool

You are using a semicolon as separator, MKMTool requires comma. Also, the name for your Quantity column should be Count, Quantity will not be recognized. So your file should look like this:

```
Count,Name,Expansion,Foil
3,Force of Virtue,Modern Horizons,
1,Fae of Wishes,Throne of Eldraine,foil
```

**Comment by roxart** [comment]
thank you worked, however I have some issues with some cards, the tool doesnt make it quite clear if the issue pops up when appraising or when inserting, some are just missing

**Comment by tomasjanak** [comment]
All import errors should be reported by the time import finishes, so if you don't see any error in the main log window, everything was imported correctly. You can verify that by directly exporting with the "include all known info". All successfully imported cards should have an idProduct filled in.

Appraising can fail for all kinds of reason, but you should get all errors in the log. Also some cards might be identified wrong if you didn't set an exact expansion and/or if you are asking for foil cards in expansions that don't have foil cards or the other way around.
