### ISSUE TITLE
Updating prices of only part of inventory

### ISSUE THREAD

**Issue by haRPyMTG** [alexander-pick/MKMTool#33]
Hello, first of all, the tool is amazing, but I ran into a problem. I'm  a private seller on MKM, but I have more then 6k unique offers, so when i update my prices the list doesn't get finished, is there a way I can still use this tool, like, update half of the inventory on day 1, the rest on day 2 of something like that (excuse me if this has already been explained somewhere, I couldn't find anything).

I hope to hear from you soon.

**Comment by haRPyMTG** [comment]
NICE! I will test this tomorrow and will let you know!

**Comment by haRPyMTG** [comment]
So i edited the source code, but how do I run the program now? If I hit f5 a screen comes up that i need to select a file to run, but there is no file selectable, how do I now start the edited MKMTOOL? (sorry, this is not really my area of knowledge).

**Comment by tomasjanak** [comment]
I am guessing you did not open the MKMTool.sln file. It should have the visual studio icon, just double click it, it will open in visual studio, than the F5 should just work, with no dialogue.

**Comment by haRPyMTG** [comment]
Im a n00b, I know, when I try what you say, i get this screen:
https://gyazo.com/72f58786c37a50127df5ff7cca84516a
When I press no I get these errors:
https://gyazo.com/5b17f8a4f29735295370219b960e889f
When I press yes I get this erros:
https://gyazo.com/d415d8c2df5ec7ac95c00dc7a34af5b7

**Comment by tomasjanak** [comment]
Never seen those, but it looks like the solution is simple, it's just some security mechanism:

https://stackoverflow.com/questions/51348919/couldnt-process-file-resx-due-to-its-being-in-the-internet-or-restricted-zone-o

**Comment by haRPyMTG** [comment]
Nice! that worked, but now im getting this error:
https://gyazo.com/5ed6b64db49b416023ed4d586356f7a0
(I followed the steps like adding the tokens and removing the _template from the name, or was that wrong?)

**Comment by tomasjanak** [comment]
Don't change the config_template.xml in MKMTool-master\MKMTool\, change it in MKMTool-master\MKMTool\bin\Debug\

Basically, the bin\Debug\ is the folder that will have your compiled version of the program, i.e. the actual .exe file and all the other necessarry files like the config file. What the "F5" does is it compiles the source files (in MKMTool-master\MKMTool\), puts the result to MKMTool-master\MKMTool\bin\Debug and then runs the MKMTool-master\MKMTool\bin\Debug\MKMTool.exe just like you would normally run it by double clicking it.

**Comment by haRPyMTG** [comment]
ugh, Im so sorry for being such a pain in the ass, but I cant see a bin folder there?

**Comment by tomasjanak** [comment]
It should be created once you compile. In the error message you posted before ( https://gyazo.com/d415d8c2df5ec7ac95c00dc7a34af5b7) it shows the path C:\users\Rick post\Desktop\MKMMASTER\MKMTool-master\MKMTool\bin\Debug 

In summary, the steps should be:

1. Download the MKMTool source, unzip (that seems to be OK)
2. Open MKMTool.sln (in visual studio).
3. Do not modify any files except for the MKMBot.cs to do the change you want.
4. Press F5. MKMTool should start after a minute and immediately crash because it can't find config.xml, but that's OK.
5. Go to ....\MKMTool\bin\Debug, config_template.xml should be there. Rename it to config.xml and fill in your credentials.
6. Press F5 in visual studio again, now it should work

**Comment by haRPyMTG** [comment]
I followed all the steps, after i change it in step 5, i run it again, but then i get the error message again (https://gyazo.com/c2bd1274b47075370478d04d4cb79b57)
When i look in the bin folder, i see that the config_template.xml is there again, with the other made config file 
https://gyazo.com/275abd3171e3c4985a7590f473529aec
What am I missing?

**Comment by tomasjanak** [comment]
Ah, my bad, didn't realize it wants both at both places. Just copy the config.xml you created in the bin folder to the ...\MKMTool-master\MKMTool, so you will have both config and config_template everywhere...maybe then it will stop complaining.

**Comment by haRPyMTG** [comment]
OMG, IT WORKED, the code to, no good numbers to back it up, because the request count got reset (midnight xD), but before the reset it was around 2k, after the reset it is 2064, I added a max on 4000 cards, so it looks like it works, I wanne thank you so much for all the help, this is amazing!

**Comment by tomasjanak** [comment]
Version 0.8. is now out, this feature is still not there, but there are instructions in the code what to easily change to set the limits: in MKMBot.cs, just change lines 654 from #if false to #if true and then set the two limits (startFrom and batchSize) to whatever number you need.

**Comment by tomasjanak** [comment]
From 0.8.2.0, commit ccac8c80d2a5f3e00989f1cfcc85f87e0f84eef1, MKMTool supports starting Price Update from where it last finished. You can also interrupt it at any time by pressing the price update button again. You cannot specify the "batch" size, it will simply run until you stop or run out of API requests, but the next day you can continue where you ended. More info in documentation https://github.com/alexander-pick/MKMTool#Price-Update.
So if you are one of the people with access to the API you can benefit from this.
