### ISSUE TITLE
CSV file from Deckbox

### ISSUE THREAD

**Issue by Broncky** [alexander-pick/MKMTool#35]
hello im new to this tool , i want to inmport my CSV file from Deckbox.org and always get errors.
are there peopple who are using both ? 
or what i the best site for MTG csv files for MKMtool.

**Comment by tomasjanak** [comment]
Hi, first make sure that the column names (first row) are one of the names listed here: https://github.com/alexander-pick/MKMTool#CSV-Card-Lists-in-MKMTool
But for a list from Deckbox it should be OK. What errors are you getting? They usually say what is wrong if it is for some particular card. Note that the names of many promo expansions (and some regular ones, like basic editions) are different on MKM and Deckbox, so if you are getting a "Unrecognized expansion..." types of error, you will have to find what that expansion is called on MKM from their product pages and do a replace all in your csv list before processing it with MKMTool.
