### ISSUE TITLE
cant connect?

### ISSUE THREAD

**Issue by roxart** [alexander-pick/MKMTool#39]
Hey all - I didn't use the tool for a while - now I wanted to start up again and get my mkm account out of sleep mode updating prices first but this happens:
https://imgur.com/a/UtZinRB
as to my knowledge there is no update in the tool right? is there any known issues about this? (I checked tokens on mkm are still the same and put into config)

and yes Thomas I still have to commit a better version of my code i know :(

**Comment by pepev12** [comment]
Hi, im using it and connecting just fine, maybe something bout internet security? i think i read something about it somewhere

**Comment by pepev12** [comment]
im compiling for some other thing and i see that error as the result of compiling, but it runs fine if i close and launch the tool normally

**Comment by roxart** [comment]
I always started the tool right out of visual studio not doin anything else so I dont know.

Any clue what it could be?

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by roxart** [comment]
can you try my version pepev? https://github.com/roxart/newmkmmychanges

**Comment by pepev12** [comment]
sure, i will in a minute,

**Comment by pepev12** [comment]
its working fine for me,
i didnt do anything, import the project, copy the config.xml file and compile,
https://imgur.com/XXFycZB
how can i help you? do you want the binary file?

**Comment by pepev12** [comment]
also i dont know what is it for, but if i press generate payed list the app crashes:

Consulte el final de este mensaje para obtener más detalles sobre cómo invocar a la depuración 
Just-In-Time (JIT) en lugar de a este cuadro de diálogo.

************** Texto de la excepción **************
System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en MKMTool.MKMBot.getActualOrderList(MainView frm1) en C:\Users\Usuario\Downloads\newmkmmychanges-master\MKMTool\MKMBot.cs:línea 508
   en MKMTool.MainView.buyListButton_Click(Object sender, EventArgs e) en C:\Users\Usuario\Downloads\newmkmmychanges-master\MKMTool\MainView.cs:línea 357
   en System.Windows.Forms.Control.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ButtonBase.WndProc(Message& m)
   en System.Windows.Forms.Button.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Ensamblados cargados **************
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4220.0 built by: NET48REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MKMTool
    Versión del ensamblado: 1.0.0.0
    Versión Win32: 0.7.0.5
    Código base: file:///C:/Users/Usuario/Downloads/newmkmmychanges-master/MKMTool/bin/Debug/MKMTool.exe
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4200.0 built by: NET48REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4200.0 built by: NET48REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4084.0 built by: NET48REL1
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4190.0 built by: NET48REL1LAST_B
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4220.0 built by: NET48REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4084.0 built by: NET48REL1
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4084.0 built by: NET48REL1
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4084.0 built by: NET48REL1
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_es_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Depuración JIT **************
Para habilitar la depuración Just In Time (JIT), el archivo de configuración de esta
aplicación o equipo (machine.config) debe tener el
valor jitDebugging establecido en la sección system.windows.forms.
La aplicación también se debe compilar con la depuración
habilitada

Por ejemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Cuando esté habilitada la depuración JIT, cualquier excepción no controlada
se enviará al depurador JIT registrado en el equipo
en lugar de controlarlo mediante el cuadro de dialogo

**Comment by roxart** [comment]
i implemented an option that gives me all the payed orders so i can import the address information directly into postal serviece to print stamps, i odnt know but i guess you have 0 open orders there

**Comment by roxart** [comment]
can you tell me how exactly you got it running? you actually compile and then run binary or start through visual studio (debug mode)?

**Comment by roxart** [comment]
i just found out if i change the visual studio setting to release mode and run it works it seems - still testing have to find my good settings for price update first!
i dunno why it doesnt work in debug mode tho

**Comment by tomasjanak** [comment]
Hi,
I just uploaded a lot of new code, please try that first and if you still have problems afterwards, I will try to help.
