### ISSUE TITLE
Pounds account

### ISSUE THREAD

**Issue by wemlock** [alexander-pick/MKMTool#40]
Will this work with the new pounds accounts. 

If not is there an update planned to add support for this?

Thanks

**Comment by tomasjanak** [comment]
They have not yet updated documentation for the API, I have just asked support to clarify how does it work, I will let you know once I get an answer.

But it will definitely work, either it will require a small change or maybe it will not require any change at all.

**Comment by wemlock** [comment]
Hopefully support will get back to you quickly

**Comment by wemlock** [comment]
Any update on this ?

**Comment by tomasjanak** [comment]
Hi, yes, I got a reply from support, the way MKMTool is written right now, the price we work with is the price in the currency of your account. So all the number you use in settings, myStock.csv etc. are in the currency of your account. Otherwise there is nothing special that needs to be done.

**Comment by tomasjanak** [comment]
Clarification added to the documentation, `€/£` is written next to settings that work directly with money in version 0.8.0.0 or newer.
