### ISSUE TITLE
API request limits ?

### ISSUE THREAD

**Issue by Deedoo34** [alexander-pick/MKMTool#42]
Hello,

First ,already mentionned by a lot of users, but still need to say it : what a great work here you've done ! ;)
Need to take time to understand but really helpfull (a lot more when I use a scan app to get list of cards, even I need to reformat the file ^^)

MkM just updated their "API rules" and, if I well understand, we still have a 500O requests per day and now an additonal limit of 600 requests per 60 seconds...
Is there a way to manage this in MkMTool ? How can we ensure a "stop" if too many requests done at a time ? (and without splitting a file to import)
We will have problems to update our stock this way ! :(

Any idea ?

Thanks for help !

David

**Comment by tomasjanak** [comment]
Hello, the limiting to 600 requests per minute has already been implemented on the "experimental" branch (https://github.com/alexander-pick/MKMTool/tree/0.8_candidate), it should get out of the experimental status next week. But you can already use it if you want to, the limiting should work correctly there.

**Comment by Deedoo34** [comment]
Too fast too furious !!! ^^
Thanks a lot for your answer... and reactivity, I'll try the experimental branch so.
Thanks again ;)

**Comment by tomasjanak** [comment]
Automatic limiter added in commit https://github.com/alexander-pick/MKMTool/commit/dc91a01aca6c5820fdc390f2a2b70f8a9f6b9b42
