### ISSUE TITLE
"Spalte -1 wurde nicht gefunden" while viewing inventory

### ISSUE THREAD

**Issue by loliman** [alexander-pick/MKMTool#48]
Hi!

I am using the MKM Tool quite a lot in the last days and it works perfectly. The only thing that does not work is viewing my inventory. Everytime I try to view it I get the error "Spalte -1 wurde nicht gefunden".

```
Fetching stock...
Finished fetching stock.
Error with listing stock in Stock View: Spalte -1 wurde nicht gefunden.
```

If I can provide more information let me know!

**Comment by tomasjanak** [comment]
Are you using the latest version? Are you working with MtG cards or some other game?

**Comment by loliman** [comment]
I am using 0.8.0.1. Only MTG.

**Comment by tomasjanak** [comment]
I have uploaded version 0.8.0.3 in which you should no longer see the error and your stock should show. However, the reason for the error is that there is some column missing in your stock, I don't know which one and why is it missing.
You should have at least the columns shown on the picture below (and some more if you have UseStockGetFile=false in your config), let me know which one is missing, thanks.
![image](https://user-images.githubusercontent.com/35869927/104507682-6e397e00-55e7-11eb-87c3-76ffb5eb9ca4.png)

**Comment by roxart** [comment]
Hey all


I haven't been using the program lately cus i have no time to update and 
transfer all my own changes to the new version - however mkm is just 
slow and haveing problems all the time like all evening today i can't 
use the website I think there could be server / hosting problems on mkm side


regards

**Comment by loliman** [comment]
I debugged the application myself and found the solution. The issue is the missing "Comment" column in my inventory. Maybe because I do not have any comments on my articles?
