### ISSUE TITLE
XCOPY problem ?

### ISSUE THREAD

**Issue by Aupaaupa** [alexander-pick/MKMTool#53]
Hi,

I had this exact same problem (https://github.com/alexander-pick/MKMTool/issues/33#issuecomment-622129741) and I guess I solved it by following the instructions you gave.
But then I hit run and I have this issue
`/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(5,5): Error MSB3073: La commande "XCOPY "/Users/thomas/Downloads/MKMTool-master/Presets" "/Users/thomas/Downloads/MKMTool-master/MKMTool/bin/Debug/Presets/" /S /Y" s'est arrêtée avec le code 127. (MSB3073) (MKMTool)`

It's probably important to add I'm running Visual Studio for Mac.

Thanks for the help !

**Comment by tomasjanak** [comment]
Xcopy is not on macos, but it should be easy to replace, it's just a command to copy files. In visual studio, open the properties of the MKMTool project (so almost the root thing, just below the Solution in the Solution Explorer), and select Build Events. You should see two almost empty windows, with only one line in the second one:

> XCOPY "$(SolutionDir)Presets" "$(TargetDir)Presets\" /S /Y

It says "copy "$(SolutionDir)Presets" to "$(TargetDir)Presets\", including all files and folders in it (/S) and don't prompt be about overwriting files (/Y). You should be able to do the same thing on mac with either the [`cp`](https://ss64.com/osx/cp.html) or [`rsync`](https://ss64.com/osx/rsync.html) command (click to go to their documentation pages). So I think it should be either:

> cp -r -f "$(SolutionDir)Presets" "$(TargetDir)Presets\"

or 

> rsync -r -u "$(SolutionDir)Presets" "$(TargetDir)Presets\"

I have tested none of these, so no promises. When all fails, you can just delete the command and copy the Preset folder manually to the MKMTool/bin/debug/ folder.

**Comment by Aupaaupa** [comment]
Thank you for helping me !
I'm sorry but i'm a total noob with Visual Studio...
I cannot even find "Build Events". 
Here is what I see in the solution explorer
<img width="301" alt="Capture d’écran 2021-02-05 à 08 36 25" src="https://user-images.githubusercontent.com/78558248/107003795-a3239580-678d-11eb-8f01-d37a81f370f0.png">

**Comment by Aupaaupa** [comment]
Okay I think I kind of understood what you meant :
I try to build MKMTool and then go double click on the error at the bottom of the page.
Then it sends me there :
<img width="2006" alt="Capture d’écran 2021-02-05 à 10 51 24" src="https://user-images.githubusercontent.com/78558248/107018196-69a85580-67a0-11eb-8185-5dbf0ced7770.png">
I don't see the XCOPY command to replace ?

**Comment by tomasjanak** [comment]
I don't know how macs work, on windows you would press right mouse button on the MKMTool you have selected in blue in the first screenshot and there go to properties. Here is how it looks on windows:
![image](https://user-images.githubusercontent.com/35869927/107082150-0cd68a80-67f4-11eb-9297-083abc8bbb5f.png)


Here is also a stackoverflow answer for where to find post build events on mac: https://stackoverflow.com/questions/53264960/pre-build-post-build-events-in-visual-studio-for-mac

**Comment by Aupaaupa** [comment]
It seems to be different on mac. Here is what I have when I right click on the solution :
<img width="371" alt="Capture d’écran 2021-02-06 à 14 55 28" src="https://user-images.githubusercontent.com/78558248/107120053-94bba380-688b-11eb-8d78-e7964433e4f1.png">
No properties...

I think i'm gonna give up to run MKM on my Mac, I don't have the skills to tweak the code and I'm doing stuff without understanding what it is, and that is never good !

BUT, I could run it using bootcamp and it worked :)
I think it is a great tool and the "check for cheap deals" feature is awesome.

I also tried the "Update Price" function (on test mode) and experienced a weird issue (let me know if I need to open a new thread for that) : the program tested a lot of card that are not in my inventory, which is about 1200 cards.
I can't be a 100% sure but it seems that there were cards that are in my wantlists. Is it possible that the tool mixes up the places to look for prices to check ?

Thanks again for your help !

**Comment by tomasjanak** [comment]
> I also tried the "Update Price" function (on test mode) and experienced a weird issue (let me know if I need to open a new thread for that) : the program tested a lot of card that are not in my inventory, which is about 1200 cards.
> I can't be a 100% sure but it seems that there were cards that are in my wantlists. Is it possible that the tool mixes up the places to look for prices to check ?
> 

That sounds very strange, nobody ever reported anything like this and I also did not see it. It would be best to start a new Issue (and close this one) where you describe exactly what you did and also if you could double check if it really were cards from the wantlist.
