### ISSUE TITLE
Request: Upload previously exported inventory to MKM retaining all data

### ISSUE THREAD

**Issue by ganiwo** [alexander-pick/MKMTool#54]
Hello and thank you for all  your efforts on this great tool! I'd like to propose an enchancement to allow an import to MKM based on previously exported inventory with all data including prices. Use case for this is when you are buying a collection or subset of collection on MKM and want to list the articles again on your account. Would also be useful for backup/restore of enitre collection.

**Comment by tomasjanak** [comment]
You can already do this with MKMTool assuming you can get the seller to give you their inventory exported by MKMTool's "View Inventory", or in some other compatible format (documentation on the file formats is [here](https://github.com/alexander-pick/MKMTool#csv-card-lists-in-mkmtool) ).
The workflow would be:

As the seller:
1. Open the View Inventory module, wait for it to load (can take some time if it is large).
2. Press the `Export to CSV...` button and choose destination for the file.
3. Send the file to the buyer

As the buyer:
1. Open it in a spreadsheet editor (MS Excel or similar) and on the first line, change the column name `Price` to `MKMTool Price` and save and close. Make sure to keep the same format (that is .csv separated by whatever you have in your config.xml as `CSVExportSeparator`). Alternatively, open it in an ordinary text editor (that can handle large files if it is large) and just replace the `"Price"` to `"MKMTool Price"` on the first line - this way you can be sure the format will stay the safe. DO include the quotation marks (the spreadsheet editor should be adding those automatically).
2. In MKMTool, open the `Price External List` module.
3. Select `Import CSV file...` and select the file you got. You don't need to change any of the default values.
4. Press `Upload to MKM`. Make sure the `Upload price` above the button has the default value, which should be `MKMTool price`. Do NOT press the `Appraise` button, that would overwrite the prices you already have.

**Comment by ganiwo** [comment]
Thank you, that's a very convenient workaround!

**Comment by ganiwo** [comment]
Getting "Selected price not computed for item" in 0.8.0.4 when trying to upload. Upload button itself is unclocked after changing the column name so assuming that workaround was applied correctly.

**Comment by tomasjanak** [comment]
The upload button is always available once import succeeds. You have the wrong column name, I think it is case sensitive, maybe that's the problem? If not, post just the first line of your file (ideally copy paste from when you open it in text editor, not excel) maybe I'll see something.

**Comment by ganiwo** [comment]
You are correct, it was a case issue on my end. I appreciate the assistance!
