### ISSUE TITLE
Request: Support for SuggestedPrice from https://api.cardmarket.com/ws/v2.0/priceguide endpoint

### ISSUE THREAD

**Issue by ganiwo** [alexander-pick/MKMTool#55]
MKM has SuggestedPrice in their price guide available for professional and powersellers. That would be great to have supported. I would be happy to help in testing this feature if needed.

**Comment by tomasjanak** [comment]
Added in version 0.8.2.0, commit 1daba63f82c619d0a5f5377143c2a47035a8a699 , along with the ability to use all the price guides. However, it is available only for commercial sellers (Cardmarket's limitation, not ours). If you have access to the API, it should work.
