### ISSUE TITLE
Prices not updating

### ISSUE THREAD

**Issue by Aupaaupa** [alexander-pick/MKMTool#56]
Hi,

Since yesterday I try to update my prices, but when I go to check on MKM, nothing changed.
I took care to have the "test mode" box unchecked.
<img width="1189" alt="Capture d’écran 2021-02-12 120642" src="https://user-images.githubusercontent.com/78558248/107762029-a5a56280-6d2c-11eb-9f91-aea3e0e3882d.png">
<img width="1122" alt="Capture d’écran 2021-02-12 à 12 10 43" src="https://user-images.githubusercontent.com/78558248/107762066-b2c25180-6d2c-11eb-8a2d-d6c26da2b5f7.png">

What am I doing wrong ?

Thank you !

**Comment by tomasjanak** [comment]
Prices are updated in batches of 100, you will see a message "[some number] articles updated successfully" when they get actually sent to MKM. Did you let the update finish?

**Comment by Aupaaupa** [comment]
To be honest I didn't pay attention if there was the message "[some number] articles updated successfully".
I know there was a bunch of 504 timeout errors, so maybe MKM was having trouble at that moment..?

However, I tried again a couple times since this issue, and the price update worked, but only for a very small part of all my cards :
On the first update, 51 prices were tested, and 26 were updated successfully (0 failed)
`Fetching stock...
--
Finished fetching stock.
Updating Prices...
35>> Fabricate (Mirrodin, French)
Current Price: 2.09, Calculated Price:1.97, based on 4 items.
1813>> Words of Waste (Onslaught, French)
Current Price: 0.99, Calculated Price:0.90, based on 4 items.
3642>> Seer's Vision (Invasion, English)
Current Price: 0.11, Calculated Price:0.14, based on 4 items.
5686>> Hurloon Minotaur (Revised, English)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
5688>> Kird Ape (Revised, English)
Current Price: 0.14, Calculated Price:0.19, based on 4 items.
5689>> Lightning Bolt (Revised, English)
NOT UPDATED - change too large: Current Price: 10.99, Calculated Price:12.00 - worldwide search!
5937>> Spell Blast (Fourth Edition, French)
Current Price: 0.5, unchanged, only 1 similar items found - worldwide search!
5952>> Birds of Paradise (Fourth Edition, English)
Current Price: 5.37, Calculated Price:4.78, based on 4 items.
6006>> Whirling Dervish (Fourth Edition, French)
Current Price: 0.16, Calculated Price:0.12, based on 4 items.
6070>> Pyrotechnics (Fourth Edition, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
6134>> Serra Angel (Fourth Edition, English)
Current Price: 0.32, Calculated Price:0.29, based on 4 items.
6178>> Howling Mine (Fourth Edition, French)
Current Price: 1.06, Calculated Price:1.04, based on 4 items.
6226>> Foul Familiar (Ice Age, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
6276>> Counterspell (Ice Age, French)
Current Price: 3.99, unchanged, only 0 similar items found - worldwide search!
6341>> Freyalise's Winds (Ice Age, English)
Current Price: 0.19, Calculated Price:0.16, based on 4 items.
6368>> Thermokarst (Ice Age, French)
Current Price: 4, unchanged, only 0 similar items found - worldwide search!
7832>> Serra Inquisitors (Homelands, French)
Current Price: 0.05, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
7903>> Soldevi Sage (V.1) (Alliances, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
7965>> Pillage (Alliances, French)
Current Price: 1.99, unchanged, only 0 similar items found - worldwide search!
8008>> Aesthir Glider (V.1) (Alliances, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
8012>> Astrolabe (V.2) (Alliances, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
8022>> Phyrexian War Beast (V.2) (Alliances, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
8232>> Hammer of Bogardan (Mirage, English)
Current Price: 0.55, Calculated Price:0.33, based on 4 items - worldwide search!
8254>> Wildfire Emissary (Mirage, French)
Current Price: 0.99, unchanged, only 0 similar items found - worldwide search!
8319>> Grinning Totem (Mirage, French)
Current Price: 0.16, Calculated Price:0.18, based on 4 items.
8480>> Fireblast (Visions, French)
Current Price: 3.5, unchanged, only 1 similar items found - worldwide search!
8485>> Hulking Cyclops (Visions, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
8510>> Infantry Veteran (Visions, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
8514>> Miraculous Recovery (Visions, French)
Current Price: 0.04, Calculated Price:0.06, based on 4 items.
8555>> Sisay's Ring (Visions, French)
Current Price: 0.05, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
8581>> Haunting Misery (Weatherlight, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
8589>> Shadow Rider (Weatherlight, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
Error with updating price of Angelic Renewal: Le délai d'attente de l'opération a expiré.
9639>> Shivan Dragon (Fifth Edition, French)
Current Price: 5.7, unchanged, only 1 similar items found - worldwide search!
11133>> Howling Mine (Sixth Edition, French)
Current Price: 1.58, Calculated Price:1.69, based on 4 items.
11589>> Tectonic Break (Mercadian Masques, English)
Current Price: 2.2, Calculated Price:2.29, based on 4 items.
12716>> Mikokoro, Center of the Sea (Saviors of Kamigawa, English)
Current Price: 2.31, Calculated Price:2.37, based on 4 items - worldwide search!
14095>> Flying Men (Time Spiral, French)
Current Price: 4.99, unchanged, only 1 similar items found - worldwide search!
15218>> Unholy Strength (Foreign Black Bordered, French)
Current Price: 0.12, Calculated Price:0.14, based on 4 items.
16083>> Swords to Plowshares (Foreign White Bordered, French)
Current Price: 1.48, Calculated Price:1.41, based on 4 items.
18057>> Elvish Archers (Introductory Two-Player Set, French)
Current Price: 0.13, Calculated Price:0.14, based on 4 items.
21192>> Lightning Bolt (Magic 2010, French)
Current Price: 1.84, Calculated Price:1.86, based on 4 items.
21965>> Expedition Map (Zendikar, French)
Current Price: 0.39, Calculated Price:0.38, based on 4 items.
22173>> Creeping Tar Pit (Worldwake, English)
Current Price: 2.05, Calculated Price:2.50, based on 4 items.
298795>> Dutiful Servants (Hour of Devastation, English)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
299862>> Underworld Dreams (Legends Italian, Italian)
NOT UPDATED - change too large: Current Price: 18.99, Calculated Price:15.00 - worldwide search!
300062>> Relic Barrier (Legends Italian, Italian)
Current Price: 0.4, Calculated Price:0.45, based on 4 items.
371820>> Zombie Army Token (Black 0/0) (V.1) (War of the Spark, English)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
400394>> Gadwick, the Wizened (Throne of Eldraine, French)
Current Price: 0.13, Calculated Price:0.11, based on 4 items.
451563>> Call of the Death-Dweller (Ikoria: Lair of Behemoths, French)
Current Price: 0.09, Calculated Price:0.08, based on 4 items.
453043>> Boneyard Lurker (Ikoria: Lair of Behemoths: Extras, English)
Current Price: 0.04, Calculated Price:0.05, based on 4 items.
466294>> Baneslayer Angel (Core 2021, French)
Current Price: 1.48, Calculated Price:1.54, based on 4 items.
Error with updating price of Defiant Strike: Le délai d'attente de l'opération a expiré.
26 articles updated successfully, 0 failed
Last Run finished: 12.02.2021 22:20:27
`
On the second update, 35 prices were tested, and 10 were updated (0 failed)
`Fetching stock...
--
Finished fetching stock.
Updating Prices...
5686>> Hurloon Minotaur (Revised, English)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
5689>> Lightning Bolt (Revised, English)
NOT UPDATED - change too large: Current Price: 10.99, Calculated Price:12.00 - worldwide search!
5937>> Spell Blast (Fourth Edition, French)
Current Price: 0.5, unchanged, only 1 similar items found - worldwide search!
5952>> Birds of Paradise (Fourth Edition, French)
Current Price: 5.6, Calculated Price:5.53, based on 3 items.
6070>> Pyrotechnics (Fourth Edition, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
6226>> Foul Familiar (Ice Age, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
6276>> Counterspell (Ice Age, French)
Current Price: 3.99, unchanged, only 0 similar items found - worldwide search!
6341>> Freyalise's Winds (Ice Age, English)
Current Price: 0.16, Calculated Price:0.19, based on 4 items.
6368>> Thermokarst (Ice Age, French)
Current Price: 4, unchanged, only 0 similar items found - worldwide search!
6441>> Battle Cry (Ice Age, English)
Current Price: 0.02, Calculated Price:0.03, based on 4 items.
7832>> Serra Inquisitors (Homelands, French)
Current Price: 0.05, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
Error with updating price of Browse: Le délai d'attente de l'opération a expiré.
7903>> Soldevi Sage (V.1) (Alliances, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
7965>> Pillage (Alliances, French)
Current Price: 1.99, unchanged, only 0 similar items found - worldwide search!
Error with updating price of Aesthir Glider (V.1): Le délai d'attente de l'opération a expiré.
8012>> Astrolabe (V.2) (Alliances, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
8022>> Phyrexian War Beast (V.2) (Alliances, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
Error with updating price of Bone Harvest: Le délai d'attente de l'opération a expiré.
8254>> Wildfire Emissary (Mirage, French)
Current Price: 0.99, unchanged, only 0 similar items found - worldwide search!
8473>> Summer Bloom (Visions, French)
Current Price: 0.21, Calculated Price:0.19, based on 4 items.
8480>> Fireblast (Visions, French)
Current Price: 3.5, unchanged, only 1 similar items found - worldwide search!
8485>> Hulking Cyclops (Visions, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
8510>> Infantry Veteran (Visions, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
8555>> Sisay's Ring (Visions, French)
Current Price: 0.05, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
8581>> Haunting Misery (Weatherlight, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
8589>> Shadow Rider (Weatherlight, French)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
9639>> Shivan Dragon (Fifth Edition, French)
Current Price: 5.7, unchanged, only 1 similar items found - worldwide search!
14079>> Desert (Time Spiral, French)
Current Price: 0.35, Calculated Price:0.37, based on 4 items.
14095>> Flying Men (Time Spiral, French)
Current Price: 4.99, unchanged, only 1 similar items found - worldwide search!
20925>> Terminate (Alara Reborn, French)
Current Price: 0.18, Calculated Price:0.19, based on 4 items.
250620>> Delver of Secrets / Insectile Aberration (Innistrad, French)
Current Price: 0.61, Calculated Price:0.59, based on 4 items.
264760>> Nekusar, the Mindrazer (V.1) (Commander 2013, French)
Current Price: 1.9, Calculated Price:2.18, based on 4 items.
298795>> Dutiful Servants (Hour of Devastation, English)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
299862>> Underworld Dreams (Legends Italian, Italian)
NOT UPDATED - change too large: Current Price: 18.99, Calculated Price:15.00 - worldwide search!
371820>> Zombie Army Token (Black 0/0) (V.1) (War of the Spark, English)
Current Price: 0.02, unchanged, only 0 similar items with a condition-matching item above them found - worldwide search!
451748>> Arcane Signet (Commander: Ikoria, English)
Current Price: 2.48, Calculated Price:2.39, based on 3 items.
470954>> Sublime Epiphany (Core 2021, French)
Current Price: 0.42, Calculated Price:0.45, based on 4 items.
10 articles updated successfully, 0 failed
Last Run finished: 13.02.2021 09:50:52
`

I have about 1200 cards, is it normal that so few cards are tested ? Aren't all the prices supposed to be tested ?

Thanks again for your help !

**Comment by tomasjanak** [comment]
The time outs are now very common, which makes Price Update very slow and unreliable, see https://github.com/alexander-pick/MKMTool/issues/47, unfortunately it looks like it is not going to get better any time soon.
But in any case, all cards should get tested so this is strange. It is possible they all get tested but you have such settings that not a lot of cards does not get updated. Do you have all logging options turned on so that you know the cards in the log are the only ones that got tested? What does the API Requests made/allowed (bottom of the window) says? MKMTool should do 1 request per card, so if you ran the price update once today, I would expect the number of made requests to be over 1200.

**Comment by Aupaaupa** [comment]
> Do you have all logging options turned on so that you know the cards in the log are the only ones that got tested?

Yes they are.

> What does the API Requests made/allowed (bottom of the window) says ?

For the first one I don't remember.
For the second one, it says 925/5000.




> says?

**Comment by tomasjanak** [comment]
You have 912 unique cards in your inventory right now so it seems they are all getting tested. The only time nothing gets written in the log when all log options are on is when the computed price is the same as the current price so they don't get updated (maybe I'll add an option to log that as well later). So either there is some strange bug, or your settings are set in a way that makes the price often come out unchanged - MKMTool does not send the update in that case. You can try settings some crazy values (with test mode turned on), like set price to max price to see something is calculated for each of your cards. It's possible your prices are simply already fine and need no adjustment.

**Comment by Aupaaupa** [comment]
Well that would make a lot of sense because I did a full update a few days ago.
So probably not many prices have changed.
I didn't know that the unchanged prices were not logged. Also I didn't realize that the API requests count had to match the number of unique cards and not the total of cards.
So I guess everything is fine :)
