### ISSUE TITLE
Price External List, Version 0.8.0.4

### ISSUE THREAD

**Issue by MartinLKoenig** [alexander-pick/MKMTool#58]
Hi, 
thx for the great tool. I am very happy for the new features that come with the new version.

That being said, I recently downloaded the new version of the Tool. 

I created a list for Kaldheim using the structure I used in old csv lists.
For example:

Count,"Name","Expansion","Card Number","Foil","Language","Condition","Rarity","Comments","","","","",""
4,"Axgard Braggart","Kaldheim","1","false","English","NM","C","3-A-1","","","","",""
1,"Battershield Warrior","Kaldheim","2","false","English","NM","U","3-A-2","","","","",""

The list is still handled correctly by the old Version 0.7.0.2.

However if uploaded to the new version I get not only the error...
"Error with reading local database files: Wrong format of the CSV file on row 153407: Der Index war außerhalb des Arraybereichs."
(even though the list should not be that long)

...but also 
Error with creating metacard: Unrecognized expansion Kaldheim, will be ignored
Error with importing line #2, identifying expansion for Axgard Braggart, article will be ignored: No card with this name found.
Error with creating metacard: Unrecognized expansion Kaldheim, will be ignored
Error with importing line #3, identifying expansion for Battershield Warrior, article will be ignored: No card with this name found.
Error with creating metacard: Unrecognized expansion Kaldheim, will be ignored

What am I missing/doing differently in the new version?

**Comment by tomasjanak** [comment]
In 0.8 was a change in the database format and also mkm actually had some errors in their database, so it has to be created anew. So before the first time you run 0.8, you have to delete the files mkminventory.csv and mkmexpansions.csv if you have them (in hindsight, I should have just used a new name...oh well). Let me know if that helped, if not, I'll investigate further.

Btw, the error with line 153407 that's not your csv, that's the database, hence the large number :)
