### ISSUE TITLE
Running the tool on debian

### ISSUE THREAD

**Issue by rasmaral** [alexander-pick/MKMTool#59]
Hello.

I Just bought a raspberry pi4 with debian installed to hope i could run the mkm tool on it because its a waste of energy on my Computer. I installed visual studio Code but i cant get the MKMTool to work. I choosed c# for debbuging. Do you might now what Else i need for Linux to work? Thanks in advance

Michael

**Comment by tomasjanak** [comment]
you need .NET, it seems it has official support for debian by microsoft, check this: https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian if that does not work you can try Mono (which is an open source version of .NET). don't know what else is needed

**Comment by rasmaral** [comment]
It didnt work. The. Net didnt install and i always got an error. So i installed Windows 10 on the raspberry pi. Now it works. Thanks for your help and keep up the good work!!!
