### ISSUE TITLE
Set minumum price of all items

### ISSUE THREAD

**Issue by loliman** [alexander-pick/MKMTool#61]
Would it be possible to add an option to set the minimum price of all items, not only rares/mythics?

Thanks in advance!

**Comment by tomasjanak** [comment]
Just add a line to your myStock.csv with nothing but the minPrice filled in, similar question answered here with more info: https://github.com/alexander-pick/MKMTool/issues/17#issuecomment-524791740

**Comment by loliman** [comment]
That works perfectly. Thanks!
