### ISSUE TITLE
Easy Price increase for privat Seller

### ISSUE THREAD

**Issue by michaCGN** [alexander-pick/MKMTool#62]
Hi,
i would like to have the feature  take my actual price  +  x  % = new price.
Is that possible?
I am sellling not a lot but i wan to increase the price by all cards on the same time...

**Comment by tomasjanak** [comment]
Adding that would be a bit of work and I don't think it is that useful for daily updates. But you can do this by exporting your inventory to csv from "View Inventory", then editing your prices in Excel (or similar software) - you can add a fixed amount/percentage easily to a whole column - and then re-importing it with the modifications by using the Price External List feature with appraisal turned off (the workflow is described here in more details: https://github.com/alexander-pick/MKMTool/issues/54#issuecomment-775395372 ).
Alternatively, you can do this directly in cardmarket in the bulk edit mode. Unfortunately, you cannot apply it at once to whole stock, so if your stock is large, the method through the csv export/import will be faster:
![image](https://user-images.githubusercontent.com/35869927/111037936-a530e200-8426-11eb-9c04-1a5c126564ec.png)

**Comment by michaCGN** [comment]
Tomasjanak,
i am impresses how fast and helpfull you answer! Thank you a lot. In my case the Screenshot is exaclty the stuff i searched.
You can use Bulk Edit Mode put there 110 % (or +/-) and click on [OK] than you only have to except the price change during clicking on the [OK] on the Table labels (in dark blue.). Than mkm will update all prices. Really nice! 
So big thx!
