### ISSUE TITLE
Error with downloading MKM inventory: Wrong format of the header of CSV file

### ISSUE THREAD

**Issue by s-hadz** [alexander-pick/MKMTool#65]
Hello guyz,

I got this issue when I am trying to Update local data  : 

![image](https://user-images.githubusercontent.com/58626006/210172026-a7714010-6b28-4397-862e-fc0eda299c2f.png)

It says there is already a column number 1 in the Data Table.

Got same error on other milestone 8.0.1

Thank you for you help,

Cheers and happy new year

**Comment by tomasjanak** [comment]
Hello, this is a bug on MKM site, reported but never fixed, I have submitted a temporary fix on our side in August in commit https://github.com/alexander-pick/MKMTool/commit/3a0c6b85dc4c2ae4044bf3d48a25c2e024fc45ba . 
I assume you are using the MKMTool you downloaded from the link in readme, it does not have this update. Either build MKMTool yourself from the latest source code or use this one: 
[MKMTool0.8.2.0_commit020822.zip](https://github.com/alexander-pick/MKMTool/files/10329027/MKMTool0.8.2.0_commit020822.zip)

**Comment by s-hadz** [comment]
Thank you @tomasjanak and the team. You rocks
