### ISSUE TITLE
Making UseStockGetFile "true" gives me a 429 error

### ISSUE THREAD

**Issue by bombehjort** [alexander-pick/MKMTool#66]
Whenever i try to update prices or view inventory, it only works when i have UseStockGetFile "false". or else i get a 429 error. Any fixes? I only want to work with magic cards, and the "games" setting don't work if UseStockGetFile is false.

**Comment by tomasjanak** [comment]
429 is [Too Many Requests](https://api.cardmarket.com/ws/documentation/API_2.0:Response_Codes). If you still have requests left (they are shown at the bottom of MKMTool as "Api requests made/allowed"), then it must be some error or wrong response code on their part, so you would need to contact the support and tell them that you get that response for 
`GET https://api.cardmarket.com/ws/v2.0/stock/file?idGame=1`

**Comment by bombehjort** [comment]
Bit of an update here: Even running the update with UseStockGetFile "false" gets me errors. It doesn't get a 429 error, but pops up 400 errors for all the cards, including the magic cards. 
![MKMTool 400 errors](https://github.com/alexander-pick/MKMTool/assets/56762489/70f9ffa6-3596-4dc1-8fc4-c73cc3f8a1bc)

**Comment by tomasjanak** [comment]
I think if you reduce ArticleCountFetched in your config file to 100 or less it should be ok.
There have been a change in the API that articles have to be fetched in batches of at most 100, used to be 1000. I will publish a fix later that allows more (up to 1000), but it also means that there is 1 API request for each 100
