### ISSUE TITLE
Any chance to add Disney Lorcana game ?

### ISSUE THREAD

**Issue by s-hadz** [alexander-pick/MKMTool#67]
Hello, 

Could you kindly add Disney Lorcana game intro MKMTool please ?

Thanks for this awesome  job !

**Comment by s-hadz** [comment]
> Hello,
> 
> Could you kindly add Disney Lorcana game intro MKMTool please ?
> 
> Thanks for this awesome job !

Trying my chance again for this request. Thank you guyz

**Comment by tomasjanak** [comment]
Added in commit e5d7996bdfba2e75acf96c8c215a2aeeedcaf10f , version 0.8.2.2 (windows binaries for download on my github https://github.com/tomasjanak/tomasjanak.github.io/blob/master/MKMTool0.8.2.2.zip)
